using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Security.Cryptography.X509Certificates;
namespace Mission_06Easton.Models
{
    public class Movie
    {
        [Key]
        //[Required]
        //[DatabaseGenerated(DatabaseGeneratedOption.Identity)] // This specifies that the ID will be generated by the database
        public int MovieId { get; set; }

        //how do I set this up to be a foreign key?
        [ForeignKey("CategoryId")]
        public int CategoryId { get; set; }
        public Category? Category { get; set; }

        //all the database stuff
        //add the rest
        //[Required]
       
        //public string CategoryName { get; set; }
         
        //public string? Subcategory { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        //ADD SOMETHING SO THIS CAN"T BE BEFORE THE 1880 year or whatever
        [Range(1888,2024, ErrorMessage = "Please enter a year between 1888 and 2024")]
        public int Year { get; set; }
        [Required]
        public string Director { get; set; }

        [Required]
        public string Rating { get; set; }

        [Required]
        public bool Edited { get; set; }

        public string? LentTo { get; set; }

        [Required]
        public bool CopiedToPlex { get; set; }

        [MaxLength(25)]
        public string? Notes { get; set; }

    }

}


//this is the database model set up
//