using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Security.Cryptography.X509Certificates;
namespace Mission_06Easton.Models
{
    public class Movie
    {
        [Key]
        //[Required]
        //[DatabaseGenerated(DatabaseGeneratedOption.Identity)] // This specifies that the ID will be generated by the database
        public int MovieId { get; set; }

        //how do I set this up to be a foreign key?
        [ForeignKey("CategoryId")]
        [Required(ErrorMessage ="Category is required")]
        public int? CategoryId { get; set; }
        public Cateogry? Category { get; set; }

        //Required for required feilds, ? for nullable feilds
      
        [Required(ErrorMessage ="Title is required")]
        public string Title { get; set; }
        [Required]
        //ADD SOMETHING SO THIS CAN"T BE BEFORE THE 1880 year or whatever
        [Range(1888,2024, ErrorMessage = "Please enter a year between 1888 and 2024")]
        public int Year { get; set; }
       //can be null
        public string? Director { get; set; }

        //[Required]
        public string? Rating { get; set; }
        //special error mesage

        [Required(ErrorMessage ="Edited is required")]
        public bool Edited { get; set; }

        public string? LentTo { get; set; }
        //error message

        [Required(ErrorMessage ="This is required")]
        public bool CopiedToPlex { get; set; }
        //limit length

        [MaxLength(25)]
        public string? Notes { get; set; }

    }

}


//this is the database model set up
//