using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Security.Cryptography.X509Certificates;
namespace Mission_06Easton.Models
{
    public class Movie
    {
        [Key]
        [Required]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // This specifies that the ID will be generated by the database
        public int MovieID { get; set; }

        //all the database stuff
        //add the rest
        public string Category { get; set; }
        public string Subcategory { get; set; }

        public string Title { get; set; }

        public int Year { get; set; }

        public string Director { get; set; }

        public string Rating { get; set; }

        public bool? Edited { get; set; }

        public string? LentTo { get; set; }

        public string? Notes { get; set; }

    }

}


//this is the database model set up
//